image: registry.gitlab.com/peachpayments/checkout-php-sdk:latest

stages:
  - test

test:
  stage: test
  tags:
    - docker
  script:
    - composer install
    - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-cobertura coverage.xml tests
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

